name: UiPath CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET (required for UiPath CLI)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Step 3: Download UiPath CLI
      - name: Download UiPath CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/UiPath/uipathcli/releases/latest/download/UiPath.CLI.Windows.zip -OutFile uipcli.zip
          Expand-Archive uipcli.zip -DestinationPath uipcli
          echo "$PWD\uipcli\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Step 4: Verify installation
      - name: Verify UiPath CLI
        run: uipcli --help

      # Step 5: Create output folder and package
      - name: Package UiPath project
        run: |
          New-Item -ItemType Directory -Force -Path "$PWD\out" | Out-Null
          uipcli package pack "$PWD" -o "$PWD\out" --autoVersion

      # Step 6: Upload package artifact
      - name: Upload UiPath Package
        uses: actions/upload-artifact@v3
        with:
          name: UiPathPackage
          path: out/*.nupkg

  deploy:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' # deploy only on manual trigger

    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: UiPathPackage
          path: out

      - name: Deploy to Orchestrator
        run: |
          uipcli package deploy out\*.nupkg `
            --url $env:UIP_ORCH_URL `
            --tenant $env:UIP_TENANT `
            --clientId $env:UIP_APP_ID `
            --clientSecret $env:UIP_APP_SECRET `
            --accountName $env:UIP_ACCOUNT `
            --folder $env:UIP_FOLDER
        env:
          UIP_ORCH_URL: ${{ secrets.UIP_ORCH_URL }}
          UIP_TENANT: ${{ secrets.UIP_TENANT }}
          UIP_APP_ID: ${{ secrets.UIP_APP_ID }}
          UIP_APP_SECRET: ${{ secrets.UIP_APP_SECRET }}
          UIP_ACCOUNT: ${{ secrets.UIP_ACCOUNT }}
          UIP_FOLDER: ${{ secrets.UIP_FOLDER }}
