name: UiPath CI/CD Simple

on:
  workflow_dispatch:

jobs:
  ci_cd:
    runs-on: windows-latest

    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Setup UiPath CLI
        uses: Mikael-RnD/setup-uipath@v2
        with:
          version: '25.4.9364.27216'

      - name: Verify CLI
        shell: pwsh
        run: |
          & uipcli --version

      - name: Pack Project
        shell: pwsh
        run: |
          & uipcli package pack "$PWD" -o "$PWD\out" --autoVersion

      - name: Deploy to Orchestrator
        shell: pwsh
        run: |
          $folder = "${{ secrets.UIP_FOLDER }}".Replace("`r`n", "").Replace("`n", "").Replace("`r", "")
          $entryPoint = "${{ secrets.UIP_ENTRY_POINT }}".Replace("`r`n", "").Replace("`n", "").Replace("`r", "")
          $appSecret = "${{ secrets.UIP_APP_SECRET }}".Replace("$","`$")
          & uipcli package deploy "$PWD\out\*.nupkg" `
            "${{ secrets.UIP_ORCH_URL }}" `
            "${{ secrets.UIP_TENANT }}" `
            -A "${{ secrets.UIP_ACCOUNT_FOR_APP }}" `
            -I "${{ secrets.UIP_APP_ID }}" `
            -S "$appSecret" `
            --applicationScope "${{ secrets.UIP_APP_SCOPE }}" `
            -o "$folder" `
            --createProcess true `
            --processName "${{ secrets.UIP_PROCESS_NAME }}" `
            --entryPointsPath "$entryPoint"

      - name: Run Job
        shell: pwsh
        run: |
          $folder = "${{ secrets.UIP_FOLDER }}".Replace("`r`n", "").Replace("`n", "").Replace("`r", "")
          $appSecret = "${{ secrets.UIP_APP_SECRET }}".Replace("$","`$")
          & uipcli job run `
            "${{ secrets.UIP_ORCH_URL }}" `
            "${{ secrets.UIP_TENANT }}" `
            -A "${{ secrets.UIP_ACCOUNT_FOR_APP }}" `
            -I "${{ secrets.UIP_APP_ID }}" `
            -S "$appSecret" `
            --applicationScope "${{ secrets.UIP_APP_SCOPE }}" `
            -o "$folder" `
            --processName "${{ secrets.UIP_PROCESS_NAME }}"
